import type { RouteNode } from './types.js';

const BANNER = `// AUTO-GENERATED — do not edit manually
// Re-generated by the file-based-routing Vite plugin on every dev start,
// file change inside src/routes/, and production build.

`;

/**
 * Convert a relative file path (from src/) to an ES import path
 * that works as a Vite dynamic import.
 *
 * e.g. "routes/blog/[slug].tsx" → "./routes/blog/[slug]"
 */
function toImportPath(relativePath: string): string {
  // Strip extension
  const withoutExt = relativePath.replace(/\.(tsx|ts|jsx|js)$/, '');
  // Ensure it starts with ./
  return withoutExt.startsWith('.') ? withoutExt : `./${withoutExt}`;
}

/**
 * Generate the lazy() call for a component file.
 *
 * Produces:
 *   async () => ({ Component: (await import('<path>')).default })
 */
function lazyComponent(filePath: string): string {
  const imp = toImportPath(filePath);
  return `async () => ({ Component: (await import('${imp}')).default })`;
}

/**
 * Indent every line of a multi-line string by `n` spaces.
 */
function indent(code: string, n: number): string {
  const pad = ' '.repeat(n);
  return code
    .split('\n')
    .map((line) => (line.trim() === '' ? '' : pad + line))
    .join('\n');
}

/**
 * Recursively generate the RouteObject literal for a single RouteNode.
 *
 * @param node  - The route node to generate code for.
 * @param depth - Current indentation depth (2 spaces per level).
 */
function generateNode(node: RouteNode, depth: number): string {
  const pad = '  '; // 2-space indent unit

  // ── Leaf route (has a filePath, no children) ─────────────────────────────
  if (!node.isCatchAll && node.filePath && node.children.length === 0 && !node.layout && !node.guard) {
    if (node.isIndex) {
      return `{ index: true, lazy: ${lazyComponent(node.filePath)} }`;
    }
    return `{ path: '${node.segment}', lazy: ${lazyComponent(node.filePath)} }`;
  }

  // ── Catch-all leaf ───────────────────────────────────────────────────────
  if (node.isCatchAll && node.filePath) {
    return `{ path: '*', lazy: ${lazyComponent(node.filePath)} }`;
  }

  // ── Directory or route-with-children ────────────────────────────────────
  // Build the innermost children array (actual routes)
  const childrenCode = generateChildren(node.children, depth + 1);

  // Wrap with layout → guard (innermost = layout, outermost = guard)
  let wrappedChildren = childrenCode;

  if (node.layout) {
    wrappedChildren = wrapWithPathlessRoute(node.layout, wrappedChildren, depth + 1);
  }

  if (node.guard) {
    wrappedChildren = wrapWithPathlessRoute(node.guard, wrappedChildren, depth + 1);
  }

  // Root node AND group nodes share the same shape: segment === '', filePath ===
  // null, isIndex === false.  Both should dissolve into their (possibly
  // guard/layout-wrapped) children — no enclosing { path } shell.
  // Note: the true root is processed in generate() directly and never reaches
  // generateNode(); this branch therefore only fires for group nodes.
  if (node.segment === '' && !node.filePath && !node.isIndex) {
    // The root node's guard/layout are the outermost wrappers.
    // wrappedChildren already contains them; return as-is.
    return wrappedChildren;
  }

  // Directory node with own filePath (index.tsx for this dir exists)
  // e.g. blog/index.tsx: the index route lives inside the children of the path node.
  const pathAttr = node.isIndex ? 'index: true' : `path: '${node.segment}'`;

  if (node.filePath && node.isIndex) {
    // This is an index file — emit as index route with lazy, children handled separately
    // Actually index nodes with children don't typically exist; skip.
    return `{ index: true, lazy: ${lazyComponent(node.filePath)} }`;
  }

  // Path namespace node (directory) with children
  const lines: string[] = [];
  lines.push('{');
  lines.push(`${pad}path: '${node.segment}',`);
  lines.push(`${pad}children: [`);
  lines.push(indent(wrappedChildren, 2));
  lines.push(`${pad}],`);
  lines.push('}');
  return lines.join('\n');
}

/**
 * Wrap a children code string inside a pathless layout route.
 *
 * Produces:
 *   {
 *     lazy: async () => ({ Component: (await import('<path>')).default }),
 *     children: [ <wrappedChildren> ],
 *   }
 */
function wrapWithPathlessRoute(filePath: string, childrenCode: string, depth: number): string {
  const pad = '  ';
  return [
    '{',
    `${pad}lazy: ${lazyComponent(filePath)},`,
    `${pad}children: [`,
    indent(childrenCode, 2),
    `${pad}],`,
    '}',
  ].join('\n');
}

/**
 * Generate the contents of a children array (comma-separated route objects).
 */
function generateChildren(nodes: RouteNode[], depth: number): string {
  return nodes.map((n) => generateNode(n, depth)).join(',\n');
}

/**
 * Generate the full `src/routes.ts` file content from a root RouteNode.
 *
 * @param root - The root node returned by the scanner.
 */
export function generate(root: RouteNode): string {
  // The root node represents src/routes/ itself.
  // Its children are the top-level routes.
  // Its guard/layout wrap everything.

  let innerChildren = generateChildren(root.children, 1);

  // Wrap with layout (inner)
  if (root.layout) {
    innerChildren = wrapWithPathlessRoute(root.layout, innerChildren, 1);
  }

  // Wrap with guard (outer)
  if (root.guard) {
    innerChildren = wrapWithPathlessRoute(root.guard, innerChildren, 1);
  }

  // The top-level routes array
  const routesArray = `[\n${indent(innerChildren, 2)},\n]`;

  return (
    BANNER +
    `import type { RouteObject } from 'react-router';\n\n` +
    `const routes: RouteObject[] = ${routesArray};\n\n` +
    `export default routes;\n`
  );
}
