import { test, expect } from '@playwright/test';

/**
 * Feature tests for the three new plugin capabilities:
 *
 *  1. error.tsx — per-directory (and root) error boundaries
 *  2. AppRoute type — verified indirectly: /dashboard/crash must resolve as a
 *     known route (it appears in the generated type union)
 *  3. _ prefix exclusion — _helpers.ts and _components/ must never become routes
 */

// ─── Feature 1: error.tsx error boundaries ──────────────────────────────────

test.describe('error.tsx — dashboard-scoped error boundary', () => {
  test('renders dashboard error boundary when a dashboard route throws', async ({
    page,
  }) => {
    // /dashboard/crash throws on render; the dashboard error boundary should catch it
    await page.goto('/dashboard/crash?auth=true');
    await expect(page.getByTestId('dashboard-error-boundary')).toBeVisible();
    await expect(page.getByTestId('dashboard-error-message')).toBeVisible();
  });

  test('dashboard error boundary is NOT visible on a healthy dashboard route', async ({
    page,
  }) => {
    await page.goto('/dashboard?auth=true');
    await expect(page.getByTestId('dashboard-error-boundary')).not.toBeVisible();
    await expect(page.getByTestId('page-dashboard')).toBeVisible();
  });

  test('dashboard error boundary is NOT visible on non-dashboard routes', async ({
    page,
  }) => {
    await page.goto('/about');
    await expect(page.getByTestId('dashboard-error-boundary')).not.toBeVisible();
  });

  test('error boundary is scoped — /about does not show dashboard error boundary on crash', async ({
    page,
  }) => {
    // The crash route only exists under /dashboard; confirm boundary scope
    await page.goto('/dashboard/crash?auth=true');
    await expect(page.getByTestId('dashboard-error-boundary')).toBeVisible();

    // Navigate away — boundary clears
    await page.goto('/about');
    await expect(page.getByTestId('dashboard-error-boundary')).not.toBeVisible();
    await expect(page.getByTestId('page-about')).toBeVisible();
  });
});

test.describe('error.tsx — root-level error boundary', () => {
  test('root error boundary file exists and build succeeds (boundary registered)', async ({
    page,
  }) => {
    // The root error boundary is registered. A healthy route should render normally.
    await page.goto('/');
    await expect(page.getByTestId('root-error-boundary')).not.toBeVisible();
    await expect(page.getByTestId('page-home')).toBeVisible();
  });
});

// ─── Feature 2: _ prefix exclusion ──────────────────────────────────────────

test.describe('_ prefix exclusion — private files and folders are not routes', () => {
  test('/_helpers does not resolve to a route (hits catch-all)', async ({
    page,
  }) => {
    await page.goto('/_helpers');
    // Should hit the catch-all 404, not a route for the helper file
    await expect(page.getByTestId('page-not-found')).toBeVisible();
  });

  test('/_components does not resolve to a route (hits catch-all)', async ({
    page,
  }) => {
    await page.goto('/_components');
    await expect(page.getByTestId('page-not-found')).toBeVisible();
  });

  test('/_components/StatCard does not resolve to a route', async ({ page }) => {
    await page.goto('/_components/StatCard');
    await expect(page.getByTestId('page-not-found')).toBeVisible();
  });

  test('all legitimate routes still work after _ exclusion is applied', async ({
    page,
  }) => {
    // Spot-check that normal routes are unaffected
    await page.goto('/about');
    await expect(page.getByTestId('page-about')).toBeVisible();

    await page.goto('/pricing');
    await expect(page.getByTestId('page-pricing')).toBeVisible();

    await page.goto('/account?member=true');
    await expect(page.getByTestId('page-account')).toBeVisible();
  });
});

// ─── Feature 3: AppRoute type — build-time verification ─────────────────────

test.describe('AppRoute type — generated type union', () => {
  test('the generated routes.ts contains the AppRoute type export', async ({
    page,
  }) => {
    // This test confirms the type was generated by verifying the app built
    // correctly (implying routes.ts with AppRoute compiled without errors).
    // We navigate to a route that only exists because it was registered,
    // proving the generated file is valid TypeScript.
    await page.goto('/dashboard/crash?auth=true');
    // The crash route is a real route — error boundary catches the throw
    await expect(page.getByTestId('dashboard-error-boundary')).toBeVisible();
  });
});
