// AUTO-GENERATED — do not edit manually
// Re-generated by the file-based-routing Vite plugin on every dev start,
// file change inside src/routes/, and production build.

import type { RouteObject } from 'react-router';

const routes: RouteObject[] = [
  {
    lazy: async () => ({ Component: (await import('./routes/layout')).default }),
    children: [
    { index: true, lazy: async () => ({ Component: (await import('./routes/index')).default }) },
    { path: 'about', lazy: async () => ({ Component: (await import('./routes/about')).default }) },
    {
      path: 'admin',
      children: [
      {
        lazy: async () => ({ Component: (await import('./routes/admin/guard')).default }),
        children: [
        {
          lazy: async () => ({ Component: (await import('./routes/admin/layout')).default }),
          children: [
          { index: true, lazy: async () => ({ Component: (await import('./routes/admin/index')).default }) },
          {
            path: 'users',
            children: [
            { index: true, lazy: async () => ({ Component: (await import('./routes/admin/users/index')).default }) },
            { path: ':id', lazy: async () => ({ Component: (await import('./routes/admin/users/[id]')).default }) }
            ],
          }
          ],
        }
        ],
      }
      ],
    },
    {
      path: 'blog',
      children: [
      {
        lazy: async () => ({ Component: (await import('./routes/blog/layout')).default }),
        children: [
        { index: true, lazy: async () => ({ Component: (await import('./routes/blog/index')).default }) },
        { path: ':slug', lazy: async () => ({ Component: (await import('./routes/blog/[slug]')).default }) }
        ],
      }
      ],
    },
    {
      path: 'dashboard',
      children: [
      {
        lazy: async () => ({ Component: (await import('./routes/dashboard/guard')).default }),
        children: [
        {
          lazy: async () => ({ Component: (await import('./routes/dashboard/layout')).default }),
          children: [
          { index: true, lazy: async () => ({ Component: (await import('./routes/dashboard/index')).default }) },
          { path: 'profile', lazy: async () => ({ Component: (await import('./routes/dashboard/profile')).default }) },
          {
            path: 'settings',
            children: [
            { index: true, lazy: async () => ({ Component: (await import('./routes/dashboard/settings/index')).default }) },
            { path: 'account', lazy: async () => ({ Component: (await import('./routes/dashboard/settings/account')).default }) },
            { path: 'security', lazy: async () => ({ Component: (await import('./routes/dashboard/settings/security')).default }) }
            ],
          }
          ],
        }
        ],
      }
      ],
    },
    { path: 'login', lazy: async () => ({ Component: (await import('./routes/login')).default }) },
    { path: 'unauthorized', lazy: async () => ({ Component: (await import('./routes/unauthorized')).default }) },
    { path: '*', lazy: async () => ({ Component: (await import('./routes/[...slug]')).default }) }
    ],
  },
];

export default routes;
